import os
from sys import audit
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def generate_ciso_ai(audit: dict) -> str:
    """
    Generates AI-powered CISO risk statement.
    Falls back if API fails.
    """

    try:
        score = audit["overall"]["score"]
        band = audit["overall"]["band"]

        if score >= 85:
            risk = "Low"
        elif score >= 70:
            risk = "Moderate"
        elif score >= 50:
            risk = "High"
        else:
            risk = "Critical"

        top_gaps = [
            f"{g['control_id']} ({g['category']})"
            for g in audit.get("top_gaps", [])[:3]
        ]

        prompt = f"""
You are a cybersecurity CISO writing a GDPR audit summary.

Organisation score: {score}/100
Risk level: {risk}
Band: {band}

Top risk areas:
{", ".join(top_gaps)}


Add a line this is generated by AI and should be reviewed by a human expert.

Write a concise, professional risk statement (120-150 words).
Include:
- Overall posture
- Key risks
- Business impact
- Priority actions

Do NOT use bullet points.

Add a line this is generated by AI and should be reviewed by a human expert.
"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",  # cheap + fast
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        #print("AI ERROR:", e)
        return None